### ISSUE TITLE
Fails to load correctly, forge server. ITooltipFlag

### ISSUE THREAD

**Issue by MikeZillaa** [DenisMasterHerobrine/AngelRing#15]
Mod fails to load on the server, causing a crash. Loads fine client-side.

> Mod File: angelring-1.16.5-1.3.4.jar
> 	Failure message: Angel Ring (angelring) has failed to load correctly
> 		java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
> 	Mod Version: 1.3.4
> 	Mod Issue URL: https://github.com/DenisMasterHerobrine/AngelRing/issues
> 	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
> Stacktrace:
> 	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_275] {}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275] {}
> 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275] {}
> 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_275] {}
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_275] {}
> 	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_275] {}
> 	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_275] {}
> 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
> 	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275] {}
> 	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.1] {re:classloading}
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_275] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}

**Comment by DenisMasterHerobrine** [comment]
Try updating to 1.3.4.1. Already hotfixed.
