### ISSUE TITLE
Not flying

### ISSUE THREAD

**Issue by Skeetle** [DenisMasterHerobrine/AngelRing#16]
Hello,
I got this issue that I can't fly.
Is there any keybind or am I doing anything wrong?

**Comment by DenisMasterHerobrine** [comment]
Hello. I cannot reproduce this issue in my world. Can you give version of this mod, Forge and Minecraft versions? Also modlist would be helpful here, because there are some mods that can cause weird behavior og Angel Ring.

**Comment by Skeetle** [comment]
Minecraft version: 1.16.5
Forge version: forge-36.1.24
I have 205 Mods installed in my modpack can I send screenshots of the mods aswell?

**Comment by DenisMasterHerobrine** [comment]
Sure, go ahead with screenshots.

**Comment by Skeetle** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/80830900/120547920-04810b80-c3f2-11eb-9d0c-52784e60a4f6.png)
![Screenshot_11](https://user-images.githubusercontent.com/80830900/120547923-0519a200-c3f2-11eb-86b8-4072487f8692.png)
![Screenshot_10](https://user-images.githubusercontent.com/80830900/120547924-05b23880-c3f2-11eb-919e-0db7737ec2bb.png)
![Screenshot_9](https://user-images.githubusercontent.com/80830900/120547925-05b23880-c3f2-11eb-9d55-38665a617432.png)
![Screenshot_8](https://user-images.githubusercontent.com/80830900/120547928-064acf00-c3f2-11eb-82d2-fb84e4e15838.png)
![Screenshot_7](https://user-images.githubusercontent.com/80830900/120547929-064acf00-c3f2-11eb-8cd9-a223ec39835c.png)
![Screenshot_6](https://user-images.githubusercontent.com/80830900/120547930-06e36580-c3f2-11eb-8544-f0d156824de5.png)
![Screenshot_5](https://user-images.githubusercontent.com/80830900/120547931-06e36580-c3f2-11eb-9ce9-f48c62ca9bc0.png)
![Screenshot_4](https://user-images.githubusercontent.com/80830900/120547932-06e36580-c3f2-11eb-85ac-0c019cc01006.png)
![Screenshot_3](https://user-images.githubusercontent.com/80830900/120547933-077bfc00-c3f2-11eb-9a4c-608611c6dfec.png)
![Screenshot_2](https://user-images.githubusercontent.com/80830900/120547936-077bfc00-c3f2-11eb-8130-13964cc3d9fe.png)
![Screenshot_1](https://user-images.githubusercontent.com/80830900/120547937-08149280-c3f2-11eb-977d-0efe1bd5fc3d.png)

**Comment by Skeetle** [comment]
those are all mods that I have installed

**Comment by oierbravo** [comment]
https://github.com/DenisMasterHerobrine/AngelRing/issues/17#issuecomment-939283442

**Comment by DenisMasterHerobrine** [comment]
This is an old issue. Closing this in favor of supporting Angel Ring 2 (however respective LTS 1.x versions is still supported)
