### ISSUE TITLE
Setting xp cost=0 doesn't prevent xp use

### ISSUE THREAD

**Issue by HammerDave** [DenisMasterHerobrine/AngelRing#22]
Running 1.2.0 alpha for 1.18 in the ATM7 modpack.
Config has XP cost set to zero, but XP is still used during flight.
The ticks per XP use doesn't seem to be working either, the XP bar drops approx each 2.5 seconds despite a much higher setting.
Edit: forgot to mention this is on a server and we're editing the config server side.

#General Angel Ring 2 configuration options.
[general]
	#Define how much XP will be drained from player when flying by wearing classic Angel Ring? Put 0 if you need to disable XP requirement for flight.
	#Range: > 0
	XPCost = 0
	#Define how much ticks is required to pass between each XP drain event of classic Angel Ring?
	#Range: > 1
	TicksPerDrain = 50000

**Comment by DenisMasterHerobrine** [comment]
Looks like I forgot to put a check for 1.18.1 version of 2.0.0.alpha.1. I'm sorry. Will be fixed asap in 2.0.0.alpha.2 for 1.18.x.

**Comment by DenisMasterHerobrine** [comment]
2.0.0.alpha.2 should fix this now. Reply here if the issue persists. Update Angel Ring 2 to a new alpha release on CurseForge.

**Comment by Thorinori** [comment]
After the update I needed to update both client and server configs for it to seem to work properly. Since I regained some xp on rejoining the server after updating the client side, I am thinking it is potentially working but not updating properly on the client side unless you change the config as well.

**Comment by 848244210** [comment]
1.19 also

**Comment by DenisMasterHerobrine** [comment]
I have fixed this in 2.0.1. Check in your modpack if this fixes this. Feel free to reopen if something goes wrong again. Now it uses server configs instead of common/client ones, since all changes are gameplay-related and changed server-side. Thank you for the report!
