### ISSUE TITLE
Can't fly without experience despite xp cost being 0.

### ISSUE THREAD

**Issue by Thorinori** [DenisMasterHerobrine/AngelRing#23]
While xp cost is set to 0 on both client and server, xp doesn't drain properly however I couldn't fly when I was out of experience (Or more accurately when the game thought I had no experience due to ATM7 having a client-side bug that registers you as having 0 experience until you gain some again after switching dimensions)

**Comment by DenisMasterHerobrine** [comment]
This is some sort of an issue out of my scope. However, there's a [mod](https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug) fixing this already.  I think I'll implement the same patch in near future since it's MIT.
