### ISSUE TITLE
Not compatible with 1.18.1

### ISSUE THREAD

**Issue by Vinyljackers** [DenisMasterHerobrine/AngelRing#26]
Hey there,
We really love this way of flying in the server.
we only figure that on 1.18.1 the server the fly ring works without xp and doesn't gen a config file to change anything.

**Comment by DenisMasterHerobrine** [comment]
Closing this in favor of supporting Angel Ring 2. If this issue still persists, feel free to reopen this issue. (however respective LTS 1.x versions is still supported)
