### ISSUE TITLE
Incompatibility with DeepMobLearning: Reforged.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [DenisMasterHerobrine/AngelRing#28]
**Angel Ring:** 1.5.0
**DML Reforged:** 1.0.1 or older are affected.
**Minecraft:** 1.18.2

## Behaviour
Angel Ring cannot do a proper flight check due to DML Reforged constantly rewriting mayFly and isFlying capabilities on it's side, making Angel Ring unusable every PlayerEntity data change. (Player places a block or changing items on the hotbar and etc.)

[Affected Code](https://github.com/YolloPlays/dmlreforged_repo/blob/60cabed1531c45f5e0ddc912ca4b12db691215d3/src/main/java/com/yollo/dmlreforged/common/events/PlayerHandler.java#L32-L87)

## Related issues
This issue is just to mention, that DML Reforged is incompatible with Angel Ring. Originally reported from my Discord server.
Issue: https://github.com/YolloPlays/dmlreforged_repo/issues/2

**Comment by EnotScript** [comment]
Is there a way to fix this? The developer is in a hurry to repair ...
