### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by FarmLander** [DenisMasterHerobrine/AngelRing#30]
crash server when i Right Click on Angel Ring

[crash-2022-06-18_15.07.55-server.txt](https://github.com/DenisMasterHerobrine/AngelRing/files/8933849/crash-2022-06-18_15.07.55-server.txt)

Server version: 1.16.5
Forge version: 1.16.5-36.2.34
Curios Version: curios-forge-1.16.5-4.0.5.3.jar

**Comment by DenisMasterHerobrine** [comment]
Hi. Thank you for the report. You're using an outdated Curios API. Switch to 4.0.8.2 instead of using 4.0.5.3.
This version can be found [here.](https://www.curseforge.com/minecraft/mc-mods/curios/files/3725386)

**Comment by FarmLander** [comment]
Sorry for the long answer, different time zone. Everything works, thank you very much!
