### ISSUE TITLE
[1.18.2] When XP requirement for Angel Ring is set to 0, you still need XP in order to fly.

### ISSUE THREAD

**Issue by barnumbirr** [DenisMasterHerobrine/AngelRing#39]
Hello,

I'm currently playing Direwolf20's 1.18 modpack (v.1.8.0, uses angelring2 v2.0,2) and have set `XPCost = 0` in `angelring2.toml` to disable the XP requirement for flight. After rebooting the server twice, this configuration parameter does not seem to be respected as flight still requires XP and the following message appears:

`You need to have XP to fly. Get more XP to fly again.`

Cheers.

**Comment by DenisMasterHerobrine** [comment]
The configs are now on per-world basis. Check in your `saves\serverconfig` folder angelring-server.toml and switch XPCost to 0 to disable it.

**Comment by barnumbirr** [comment]
Hello,

got it. For some reason, when I edit `world/serverconfig/angelring-server.toml`, an empty `world/serverconfig/angelring-server.toml.bak` is created and my modifications get dropped. Is this a bug or could this be an issue with the server provider (OMGServ.com)?

Cheers.
