### ISSUE TITLE
Crashes EVERY time I try to put the angel ring in the spot for it, latest file for 1.16.5

### ISSUE THREAD

**Issue by EbonyHart** [DenisMasterHerobrine/AngelRing#41]
![image](https://user-images.githubusercontent.com/110326101/182014570-29410124-beed-4143-8107-953dc58f3028.png)

I don't know what it is or what's wrong with the file or whatever, but this is getting so irritating!

**Comment by DenisMasterHerobrine** [comment]
Thanks for the report. Probably you're using an outdated Curios API version. Switch to 4.0.8.2 or higher instead of using an outdated one.
This version can be found [here.](https://www.curseforge.com/minecraft/mc-mods/curios/files/3725386)
Probably a duplicate of #30.
