### ISSUE TITLE
Setting XPCost to 0 on the config file doesn't disable XP requirement 

### ISSUE THREAD

**Issue by kaanyalova** [DenisMasterHerobrine/AngelRing#42]
Minecraft : 1.18.2
Forge: 40.1.53
Angel Ring 2: 2.0.1

**Comment by DenisMasterHerobrine** [comment]
Thanks for the report. Firstly, update to 2.0.2 to ensure you're using latest version of the mod. Also note that as of 2.0.1, Angel Ring uses per-world configs based in your `world` folder, so it need to be edited manually from `serverconfig` folder if it's an existing world or use `serverconfig` folder in the server's root folder in case you're not generated a world yet. Reopen in case you ereally experience this issue in 2.0.2, even changed `XPCost` to `0` in `angelring-server.toml` file
