### ISSUE TITLE
Even though the Angel Ring is in Classic mode, it still give this message when having 0 XP

### ISSUE THREAD

**Issue by PinkLasagna03** [DenisMasterHerobrine/AngelRing#56]
Take a look at the screenshots; 
![2024-08-20_03 12 42](https://github.com/user-attachments/assets/6d88534e-c0c6-49ed-b56e-fada191adef3)
![2024-08-20_03 12 54](https://github.com/user-attachments/assets/f3219fa5-d080-409a-bf74-7e0569978903)

Version; 1.20.1, 2.2.2

**Comment by VendoAU** [comment]
Set `XP Warning Level` to `-1` in the config to disable it

**Comment by DenisMasterHerobrine** [comment]
Fixed in 2.3.0. A release should come soon on CF.
