### ISSUE TITLE
Energetic Angel ring in 1.20.1-2.3.0 (ATM9 0.3.3a) isnt working

### ISSUE THREAD

**Issue by Reimariss** [DenisMasterHerobrine/AngelRing#57]
Energetic Angel Ring just lets me fly for a blink and then drops me back to the ground

**Comment by pietro-lopes** [comment]
Can confirm this, this happens because when you start flying, it consumes energy, changing NBT, and Curios checks if item still matches, and it fails to match (NBT changed) and triggers the `onUnequip` function that causes you to lose flying ability.

**Comment by DenisMasterHerobrine** [comment]
Thanks for the report. This is probably due to an introduced check for long values. Will investigate that today.

**Comment by DenisMasterHerobrine** [comment]
Fixed in 2.3.1. Update to it from 2.3.0 and you should be fine.
