### ISSUE TITLE
[1.14.4] Angel Ring seems to be overridding any other flight modules from any other mod w/ flight.

### ISSUE THREAD

**Issue by Gbergz** [DenisMasterHerobrine/AngelRing#7]
Seems like the Angel Ring is overwritting/overridding anything else that has to do with Flight. For example the Flight Augment from Mystical Agriculture won't work with this mod installed. Likewise with anything else that adds flight.
And the 'Orb of Temporary Flight' from 'Forbidden & Arcanus' is also affected by this. (As I said seems to be any mod with flight.)

Removing the mod solves this issue.

Is this issue known?

**Forge**: *28.1.107*
**MC**: *1.14.4*
**Mod-Version**: *1.1.0-pre2*

**Comment by DenisMasterHerobrine** [comment]
>  This is a very known issue since the creation of the mod. This is already fixed in rewritten version, currently you can't download it, but I hope I can release it soon with new additions for the mod. Sorry for this issue, I have not so much time atm to update my mods.
(copied from curseforge)
I'll keep this issue open. because rewritten version is currently not available in public.

**Comment by DenisMasterHerobrine** [comment]
Fixed in 1.1.0, write here if anything breaks again, but it shouldn't disable flight constantly now. :)
