### ISSUE TITLE
[1.16.1] Mekanism v10 breaks flying system

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [DenisMasterHerobrine/AngelRing#9]
Mekanism is disabling flight from Angel Ring after flying for a 0.5-1 second.

Mekanism: 10.0.0
Forge: 32.0.63
Angel Ring: 1.3.0

Any help is appreciated.

**Comment by pupnewfster** [comment]
This is on our end (Mekanism), and I will try to make sure to fix this for 10.0.2

**Comment by DenisMasterHerobrine** [comment]
All is fine. Thanks for the answer, I'll close this issue when this gets fixed.

**Comment by pupnewfster** [comment]
This is sort of fixed now on our end (we haven't released 10.0.2 quite yet, will comment again when we do likely later today or tomorrow), but now I believe angel ring is breaking other mods as well. In terms of it is now (10.0.2) possible to fly with Mekanism installed using the angel ring; however, it is not possible to fly using Mekanism's meka suit when a gravitational modulator is installed if this mod is installed as well, removing the angel ring mod allows flight via the meka suit.

**Comment by DenisMasterHerobrine** [comment]
Currently I haven't found any other mods preventing flight. (for example: Rings of Ascension works fine, AzureDoom's Angel Ring have the same logic as my mod and works fine too)  I can make a warning for Angel Ring if Mekanism is present in the modpack to re-equip the meka suit.

**Comment by pupnewfster** [comment]
I wouldn't worry about it, it is on our end and something I can probably make adjustments for to handle.

**Comment by pupnewfster** [comment]
Just released 10.0.2, which fixes Mekanism breaking your flight system (sorry again for that). Also managed to get it so that if both forms of flight are being used that removing the angel ring from the inventory properly doesn't even drop the player out of flight.

**Comment by DenisMasterHerobrine** [comment]
Thank you very much for fixing this and releasing 10.0.2! Closing this issue, since this is fixed in 10.0.2.
